### ISSUE TITLE
metrics: Feature planning, umbrella issue

### ISSUE THREAD

**Issue by bzub** [cloudnativelabs/kube-router#66]
I got excited about metrics since #65 landed, so this issue is just for mapping out short and long-term goals for kube-router metrics. Once we agree on the the abstract goals I will create issues to track their implementation.  I will edit this issue with any changes we discuss.

#### Configuration
- [x] Add a `--metrics-port` option to change the port.
  - `--metrics-port=0` means disabled. Default port should be uncommon.
- [ ] Provide a k8s Service definition for kube-router metrics port to our example manifests
- [ ] Provide a [ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#servicemonitor) definition to support prometheus-operator users

#### Additional Metrics (Basic)
- [ ] BGP basics. See: [gobgp monitor](https://github.com/osrg/gobgp/blob/master/docs/sources/cli-command-syntax.md#monitor)
  - Peering/Neighbor status changes
  - RIB changes
- kube-router app metrics
  - [x] error counter
  - [ ] iptable rules counter

#### Additional Metrics (Advanced/Debugging)
Could use or draw inspiration from [k8sconntrack](https://github.com/DongyiYang/k8sconntrack)
- Low level conntrack
- TCP/UDP
- iptable stats
- other /proc metrics within the scope of Nodes, Services, Endpoints and Pod networking

#### Features and Configuration
- [x] Create a Grafana dashboard to quickly visualize metrics
  - Related to network visualization proposal in #12 
- [ ] Support annotations to enable metrics per-service
  - This is to support adding CPU intensive metrics and debugging scenarios, to be implemented in another issue.

**Comment by murali-reddy** [comment]
@bzub excellent set of goals. i think short term goals can be stright away fixed.

**Comment by aauren** [comment]
Closing as stale. Some prometheus metrics have been added, and while there is still some stuff that could be done from this checklist, I think that it would be better served in a new ticket that takes the current state into account.
